language: python 

services: 
  - postgresql

python: 
  - "3.6"


install: 
  - pip install -r requirements.txt
  - pip install coveralls 
  - pip install nose


before_script: 

  - psql -c "CREATE DATABASE teststoremager;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

script: 
  - nosetests  --with-coverage --cover-package=app/api

after_success:
  - coveralls